#!/bin/bash
scrot -o -F /tmp/screenshot.png
feh -x -F /tmp/screenshot.png &
id=$!
scrot -s -f -l mode=edge --line width=3 'screenshot_%Y%m%d_%H%M%S.png' -e 'mkdir -p ~/screenshots && mv $f ~/screenshots && xclip -selection clipboard -t image/png -i ~/screenshots/`ls -1 -t ~/screenshots | head -1`'
kill $id
